version: '3'
services:
  storage:
    image: influxdb:1.7
    container_name: influxdb
    hostname: influxdb
    ports:
      - "2003:2003"
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb   # persistent storage
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INIT_USERS=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=ADMIN
      - INFLUXDB_ADMIN_PASSWORD=ADMIN123
      - INFLUXDB_LOGGING_LEVEL=error
    restart: on-failure

  view:
    image: grafana/grafana:6.7.0
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana   # persistent storage
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=gadmin
    restart: on-failure

  ci:
    build: ./jenkins
    container_name: jenkins
    hostname: jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home    # persistent storage
      - /var/run/docker.sock:/var/run/docker.sock   # Docker daemon UNIX socket link
